// List of all countries with their codes
export const countries = [
  { name: "United States", code: "+1" },
  { name: "United Kingdom", code: "+44" },
  { name: "India", code: "+91" },
  { name: "United Arab Emirates", code: "+971" },
  { name: "Canada", code: "+1" },
  { name: "Australia", code: "+61" },
  { name: "Germany", code: "+49" },
  { name: "France", code: "+33" },
  { name: "Brazil", code: "+55" },
  { name: "China", code: "+86" },
  { name: "Japan", code: "+81" },
  { name: "South Africa", code: "+27" },
  { name: "Pakistan", code: "+92" },
  { name: "Bangladesh", code: "+880" },
  { name: "Russia", code: "+7" },
  { name: "Mexico", code: "+52" },
  { name: "Italy", code: "+39" },
  { name: "Spain", code: "+34" },
  { name: "Turkey", code: "+90" },
  { name: "Saudi Arabia", code: "+966" },
  { name: "Singapore", code: "+65" },
  { name: "Malaysia", code: "+60" },
  { name: "Indonesia", code: "+62" },
  { name: "Philippines", code: "+63" },
  { name: "Egypt", code: "+20" },
  { name: "Nigeria", code: "+234" },
  { name: "Argentina", code: "+54" },
  { name: "Netherlands", code: "+31" },
  { name: "Sweden", code: "+46" },
  { name: "Switzerland", code: "+41" },
  { name: "Poland", code: "+48" },
  { name: "Norway", code: "+47" },
  { name: "Denmark", code: "+45" },
  { name: "Finland", code: "+358" },
  { name: "Ireland", code: "+353" },
  { name: "New Zealand", code: "+64" },
  { name: "South Korea", code: "+82" },
  { name: "Israel", code: "+972" },
  { name: "Thailand", code: "+66" },
  { name: "Vietnam", code: "+84" },
  { name: "Greece", code: "+30" },
  { name: "Portugal", code: "+351" },
  { name: "Belgium", code: "+32" },
  { name: "Austria", code: "+43" },
  { name: "Czech Republic", code: "+420" },
  { name: "Hungary", code: "+36" },
  { name: "Romania", code: "+40" },
  { name: "Ukraine", code: "+380" },
  { name: "Chile", code: "+56" },
  { name: "Colombia", code: "+57" },
  { name: "Peru", code: "+51" },
  { name: "Venezuela", code: "+58" },
  { name: "Morocco", code: "+212" },
  { name: "Kenya", code: "+254" },
  { name: "Ghana", code: "+233" },
  { name: "Ethiopia", code: "+251" },
  { name: "Tanzania", code: "+255" },
  { name: "Uganda", code: "+256" },
  { name: "Algeria", code: "+213" },
  { name: "Sudan", code: "+249" },
  { name: "Iraq", code: "+964" },
  { name: "Afghanistan", code: "+93" },
  { name: "Nepal", code: "+977" },
  { name: "Sri Lanka", code: "+94" },
  { name: "Myanmar", code: "+95" },
  { name: "Cambodia", code: "+855" },
  { name: "Laos", code: "+856" },
  { name: "Mongolia", code: "+976" },
  { name: "Kazakhstan", code: "+7" },
  { name: "Uzbekistan", code: "+998" },
  { name: "Turkmenistan", code: "+993" },
  { name: "Kyrgyzstan", code: "+996" },
  { name: "Tajikistan", code: "+992" },
  { name: "Belarus", code: "+375" },
  { name: "Georgia", code: "+995" },
  { name: "Armenia", code: "+374" },
  { name: "Azerbaijan", code: "+994" },
  { name: "Lithuania", code: "+370" },
  { name: "Latvia", code: "+371" },
  { name: "Estonia", code: "+372" },
  { name: "Slovakia", code: "+421" },
  { name: "Slovenia", code: "+386" },
  { name: "Croatia", code: "+385" },
  { name: "Serbia", code: "+381" },
  { name: "Montenegro", code: "+382" },
  { name: "Bosnia and Herzegovina", code: "+387" },
  { name: "North Macedonia", code: "+389" },
  { name: "Bulgaria", code: "+359" },
  { name: "Albania", code: "+355" },
  { name: "Luxembourg", code: "+352" },
  { name: "Iceland", code: "+354" },
  { name: "Malta", code: "+356" },
  { name: "Cyprus", code: "+357" },
  { name: "Liechtenstein", code: "+423" }
];
